import "./globals.css";
import { Roboto_Mono } from "next/font/google";
import Link from "next/link";

const roboto = Roboto_Mono({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <header className='relative header bg-rick-morty-bg h-screen'>
          <div className='overlay absolute top-0 left-0 right-0 h-screen bg'>
            <nav className='navbar text-white'>
              <ul className='flex p-8 gap-4 justify-center item-center'>
                <li className='text-xl'>
                  <Link href='/'>Home</Link>
                </li>
                <li className='text-xl'>
                  <Link href='/Characters'>Character</Link>
                </li>
                <li className='text-xl'>
                  <Link href='/episodes'>Episode</Link>
                </li>
                <li className='text-xl'>
                  <Link href='/location'>Location</Link>
                </li>
              </ul>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
