import "./globals.css";
import { Roboto_Mono } from "next/font/google";
import Link from "next/link";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

const roboto = Roboto_Mono({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <Navbar />
        {children}

        <Footer />
      </body>
    </html>
  );
}
